In [53]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in c:\users\nam\appdata\local\programs\python\python310\lib\site-packages (2.3.2)

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\Nam\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nam\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\nam\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\nam\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nam\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\nam\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [20]:
import pandas as pd

# # If the file has a header row:
df = pd.read_csv(r"filtered_data that can be used\the first three og datasets\roam_crawl_normalized.csv")
df

,english,french
0,café and souvenir shop available after your tour,café et boutique de souvenirs disponibles aprè...
1,weather and meteo conditions on wednesday 05 j...,les conditions climatiques et météo sur le mer...
2,spat hotel ashdod is a love hotel located in a...,"4 commentaires situé à ashdod, le love hôtel s..."
3,but illustrations of the french edition were t...,mais les illustrations de l'edition francaise ...
4,the terrace outside is unfortunately a bit tir...,la terrasse extérieure est malheureusement un ...
...,...,...
4181999,"get prices, times and duration for the journey...","obtenir les prix, les horaires et la durée du ..."
4182000,a haven of peace.,véritable havre de paix.
4182001,"to join viki1212 in private show, choose your ...","pour rejoindre viki1212 en show privé, choisis..."
4182002,climate change is altering our planet. signifi...,les changements climatiques affectent notre pl...
4182003,26 was launched at a colloquium on the philoso...,26 a été lancé lors d’un colloque sur la philo...

In [ ]:
# import pandas as pd

# MAX_LINES = 2_000_000

# # Read up to 1 million lines from the French file
# with open('OpenSubtitles.en-fr.fr', 'r', encoding='utf-8') as f_fr:
#     french_sentences = [line.strip() for _, line in zip(range(MAX_LINES), f_fr)]

# # Read up to 1 million lines from the English file
# with open('OpenSubtitles.en-fr.en', 'r', encoding='utf-8') as f_en:
#     english_sentences = [line.strip() for _, line in zip(range(MAX_LINES), f_en)]

# # Make sure both have the same number of lines
# assert len(french_sentences) == len(english_sentences), "Files are not aligned!"

# # Create a DataFrame
# df = pd.DataFrame({
#     'french': french_sentences,
#     'english': english_sentences
# })

# # Preview
# df

,french,english
0,Précédemment...,"Do you wanna call your daddy? Yeah, I wanna te..."
1,"- Oui, je veux lui dire que ça va.",Okay.
2,Lizzy...,"Lizzy, be careful of your husband."
3,Sois prudente avec ton mari.,I can only lead you to the truth.
4,Je peux seulement te mener vers la vérité.,I can't make you believe it.
...,...,...
1999995,- J'aime regarder les jolies filles...,- I like to look pretty girls ...
1999996,- Qui n'aime pas ça ?,"""Who does not like that?"""
1999997,"Buenos dias, mademoiselle.","Goodmorning,miss."
1999998,Nous allons parler un peu.,- We'll talk for a bit.
1999999,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [ ]:
# import pandas as pd

# data = []
# with open("crawl data corpus (dont know how to import this because its too big).txt", "r", encoding="utf-8") as f:
#     for i, line in enumerate(f):
#         # Example: assume tab-separated source and target
#         parts = line.rstrip('\n').split('\t')
#         if len(parts) == 2:
#             data.append(parts)
#         if i >= 1_000_000:  # Only load the first million lines
#             break

# df = pd.DataFrame(data, columns=["english", "french"])
# df

,english,french
0,Find the best flight Bristol - Calvi on our Br...,Afin de trouver le vol Brest Calvi le plus ada...
1,Brake(F/R): Disc/ Hydraulic Disc,Frein (F/R) : Disque hydraulique
2,"Mexico Mr. Jose Antonio Meade, State Secretary...","Mexique M. José Antonio Meade, Secrétaire d'Et..."
3,"• To educate landowners as well as the public,...",• Instruire les propriétaires fonciers et le p...
4,Rental holidays PRALOGNAN LA VANOISE apartment...,Location vacances PRALOGNAN LA VANOISE apparte...
...,...,...
999996,Platforms: Genres: Graphics: 3D Labels: Home D...,Plate-formes: Genres: Graphiques: 3D Étiquette...
999997,Water quality Water from the tap is surely set...,Qualité de l'eau L'eau du robinet est sûrement...
999998,"welcoming the ICRC's new study on "" Arms Avail...",accueillant favorablement la nouvelle étude du...
999999,"Education in Honduras From Wikipedia, the free...","Une page de Wikipédia, l'encyclopédie libre."
1000000,Sheet metal steel K 5100,Tôle en acier K 5100

In [ ]:
# import pandas as pd

# data = []
# with open("crawl.txt", "r", encoding="utf-8") as f:
#     for i, line in enumerate(f):
#         # if i >= 10_000_000:
#         #     break
#         src_tgt = line.rstrip('\n').split('\t')
#         if len(src_tgt) == 2:
#             data.append(src_tgt)

# df = pd.DataFrame(data, columns=["english", "french"])
# df

,english,french
0,Brake(F/R): Disc/ Hydraulic Disc,Frein (F/R) : Disque hydraulique
1,"• To educate landowners as well as the public,...",• Instruire les propriétaires fonciers et le p...
2,Rental holidays PRALOGNAN LA VANOISE apartment...,Location vacances PRALOGNAN LA VANOISE apparte...
3,Café and souvenir shop available after your tour,Café et boutique de souvenirs disponibles aprè...
4,Weather and meteo conditions on Wednesday 05 J...,Les conditions climatiques et Météo sur Le Mer...
...,...,...
7787308,"""International transport order"" form (German v...",Formulaire «Ordre de transport international» ...
7787309,Landau: Did you do something bad?,Landau: Avez-vous faire quelque chose de mal?
7787310,Climate change is altering our planet. Signifi...,Les changements climatiques affectent notre pl...
7787311,26 was launched at a colloquium on the philoso...,26 a été lancé lors d’un colloque sur la philo...
7787312,Used sailing yachts OYSTERMAN - Sailing yachts...,Modèles de voiliers OYSTERMAN d'occasion - Ann...

In [4]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

In [5]:
# Check for duplicates in the 'english' column
english_duplicates = df[df['english'].duplicated(keep=False)]
print("Duplicates in 'english' column:")
print(english_duplicates)

# # Check for duplicates in the 'french' column
french_duplicates = df[df['french'].duplicated(keep=False)]
print("Duplicates in 'french' column:")
print(french_duplicates)

Duplicates in 'english' column:
                                     french             english
1        - Oui, je veux lui dire que ça va.               Okay.
12                        Je te le promets.      I promise you.
15                                 Dégagez.              Clear.
19                               C'est bon.          It's okay.
20                               C'est bon.        You're okay.
...                                     ...                 ...
1824067                             Prêts !        Do not move!
1824073                              Pigé ?  Do you understand?
1824082                             Salut !      - How are you?
1824094                  Ou peut-être Lucy.  - Does not matter.
1824098                   - Un beau corps ?        - Fantastic.

[248330 rows x 2 columns]
Duplicates in 'french' column:
                        french                  english
12           Je te le promets.           I promise you.
15                    Dégagez.                   Clear.
19                  C'est bon.               It's okay.
20                  C'est bon.             You're okay.
21                      Chut !             You're okay.
...                        ...                      ...
1824067                Prêts !             Do not move!
1824073                 Pigé ?       Do you understand?
1824081  N'est-ce pas génial ?      Is not that great ?
1824082                Salut !           - How are you?
1824087  Je me demandais si...  I was thinking that ...

[329231 rows x 2 columns]

In [6]:
import re

# Define a regex pattern for special characters (excluding basic punctuation and space)
pattern = r'[^\w .,!?\'"’–-“$€£¥₹%％”‘\t&*()\-+=@#<>:;\/\\\[\]{}|^~`…]'  # Added more characters


# Find rows to be removed
removed = df[df['english'].str.contains(pattern, regex=True) | df['french'].str.contains(pattern, regex=True)]

# Print the removed rows
print("Rows removed due to special characters:")
print(removed)
print(len(removed))

Rows removed due to special characters:
                                                    french  \
719                     FIN DE L'ÉPISODE 2 © Varhiv 2024 |
1153     Notre première histoire se passe à l'époque ac...
1154     Dans l'Ouest, un groupe de femmes ambitieuses ...
1163     Il est un âge où l'on ne tolère ni la jeunesse...
1164     Les "Soeurs moralisatrices" ont convaincu Mlle...
...                                                    ...
1823504  ♪ Je suis tombée ♪ ♪ amoureuse pour la premièr...
1823505         ♪ Chaque fois que tu me fais frissonner, ♪
1823506                  ♪ c'est comme la première fois. ♪
1823507  ♪ Le moment est merveilleux ♪ ♪ et la sensatio...
1823508  ♪ Je suis tombée amoureuse ♪ ♪ pour la premièr...

                                                   english
719                       END OF EPISODE 2 © Varhiv 2024 |
1153     ¶ Our first story...out of the cradle of the p...
1154     ¶ In a western city we find certain ambitious ...
1163               ¶ Age intolerant of youth and laughter.
1164     ¶ "The vestal virgins of Uplift" succeed in re...
...                                                    ...
1823504  Ifellin love for the first time,  andalsoforth...
1823505                            Everytimeyoucheermeup ,
1823506                        It'slikeit 'sthefirsttime .
1823507      Themomentis wonderful and the feeling is new.
1823508  Ifellin love for the first time,  butalsoforth...

[22138 rows x 2 columns]
22138

In [7]:
# Apply the filter to keep only valid rows
mask = ~df['english'].str.contains(pattern, regex=True) & ~df['french'].str.contains(pattern, regex=True)
df = df[mask].reset_index(drop=True)
df

,french,english
0,Précédemment...,"Do you wanna call your daddy? Yeah, I wanna te..."
1,"- Oui, je veux lui dire que ça va.",Okay.
2,Lizzy...,"Lizzy, be careful of your husband."
3,Sois prudente avec ton mari.,I can only lead you to the truth.
4,Je peux seulement te mener vers la vérité.,I can't make you believe it.
...,...,...
1801962,- J'aime regarder les jolies filles...,- I like to look pretty girls ...
1801963,- Qui n'aime pas ça ?,"""Who does not like that?"""
1801964,"Buenos dias, mademoiselle.","Goodmorning,miss."
1801965,Nous allons parler un peu.,- We'll talk for a bit.
1801966,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [51]:
# Regex pattern: any word with two consecutive capital letters
pattern = r'\b\w*[A-Z]{2,}\w*\b'

# Find rows to be removed
removed = df[df['english'].str.contains(pattern, regex=True) | df['french'].str.contains(pattern, regex=True)]

print("Rows removed due to consecutive capital letters:")
print(removed)
print(len(removed))

Rows removed due to consecutive capital letters:
                                                   english  \
36       Should be jrm of course, getting old now to me...
104      The clock will be run down to the last second ...
184      Maybe, but we sell a total of £270 billion wor...
389      Funny because singapore has just signed a free...
454      Even more subsidies will be needed for farmers...
...                                                    ...
1288963  By the canadian government for the usa is the ...
1288964  The usa started this problem with canada, chin...
1288965  Point one the usa has not prove that meng of h...
1288970  Canada which is a pawn for the usa, should cha...
1288973  Easpically business that is close to the usa b...

                                                    french
36       Ça devrait être bien sûr JRM, de vieillir main...
104      L'horloge sera tombée jusqu'à la dernière seco...
184      Peut-être, mais nous vendons au total 270 mill...
389      C'est drôle parce que Singapour vient de signe...
454      Des subventions encore plus importantes seront...
...                                                    ...
1288963  Par le gouvernement canadien pour les USA est ...
1288964  L'USA a commencé ce problème avec le canada, l...
1288965  Point un l'USA n'a pas prouvé que la meng de h...
1288970  Le Canada qui est un pion pour les USA, devrai...
1288973  Des affaires éparpillées qui sont proches de l...

[7386 rows x 2 columns]
7386

In [ ]:
# Remove those rows from the DataFrame
mask = ~df['english'].str.contains(pattern, regex=True) & ~df['french'].str.contains(pattern, regex=True)
df = df[mask].reset_index(drop=True)
df

In [8]:
# Create mask for valid length ratio
mask = (
    (df['english'].str.len() < 2 * df['french'].str.len()) &
    (df['french'].str.len() < 2 * df['english'].str.len())
)

# Find and print rows to be removed
removed = df[~mask]
print("Rows removed due to sentence length ratio > 2:1:")
print(removed)
print(len(removed))

Rows removed due to sentence length ratio > 2:1:
                                                    french  \
0                                          Précédemment...
1                       - Oui, je veux lui dire que ça va.
2                                                 Lizzy...
8        Vous avez menacé de me dire la vérité sur mon ...
16                             Dêpechez-vous! 45 secondes.
...                                                    ...
1801865                        Au revoir et bonne chance !
1801918          Vous voulez vous joindre à nous, M'dame ?
1801935                                             Pigé ?
1801944                                            Salut !
1801945                              Oh, salut l'étranger.

                                                   english
0        Do you wanna call your daddy? Yeah, I wanna te...
1                                                    Okay.
2                       Lizzy, be careful of your husband.
8           Since the day we met. And I'm ready to listen.
16                                             45 seconds.
...                                                    ...
1801865                                          - Thanks.
1801918                                 "You can join us."
1801935                                 Do you understand?
1801944                                     - How are you?
1801945        - Hello strange. I can help with something?

[141664 rows x 2 columns]
141664

In [9]:
# Apply the filter
df = df[mask].reset_index(drop=True)
df

,french,english
0,Sois prudente avec ton mari.,I can only lead you to the truth.
1,Je peux seulement te mener vers la vérité.,I can't make you believe it.
2,Je ne peux pas te forcer à y croire.,She's calling herself jolene parker.
3,Elle s'appelle Jolène Parker.,"Elizabeth keen is not your wife, she's your ta..."
4,"Elizabeth Keen n'est pas ta femme, elle est ta...",You've been threatening to tell me the truth a...
...,...,...
1660298,- J'aime regarder les jolies filles...,- I like to look pretty girls ...
1660299,- Qui n'aime pas ça ?,"""Who does not like that?"""
1660300,"Buenos dias, mademoiselle.","Goodmorning,miss."
1660301,Nous allons parler un peu.,- We'll talk for a bit.
1660302,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [10]:
# Create mask for valid sentence length
mask = (
    (df['english'].str.split().str.len() > 5) & (df['english'].str.split().str.len() <= 100) &
    (df['french'].str.split().str.len() > 5) & (df['french'].str.split().str.len() <= 100)
)

# Print rows that will be removed
removed = df[~mask]
print("Rows removed due to sentence length (<5 or >100 words):")
print(removed)
print(len(removed))

Rows removed due to sentence length (<5 or >100 words):
                                       french  \
0                Sois prudente avec ton mari.
2        Je ne peux pas te forcer à y croire.
3               Elle s'appelle Jolène Parker.
7                            Le reste suivra.
8                           Je te le promets.
...                                       ...
1660295                     Une sacrée fille.
1660296                     - Un beau corps ?
1660299                 - Qui n'aime pas ça ?
1660300            Buenos dias, mademoiselle.
1660301            Nous allons parler un peu.

                                                   english
0                        I can only lead you to the truth.
2                     She's calling herself jolene parker.
3        Elizabeth keen is not your wife, she's your ta...
7                                      The rest will come.
8                                           I promise you.
...                                                    ...
1660295                         - How is she? Good figure?
1660296                                       - Fantastic.
1660299                          "Who does not like that?"
1660300                                  Goodmorning,miss.
1660301                            - We'll talk for a bit.

[904607 rows x 2 columns]
904607

In [11]:
df = df[mask].reset_index(drop=True)
df

,french,english
0,Je peux seulement te mener vers la vérité.,I can't make you believe it.
1,"Elizabeth Keen n'est pas ta femme, elle est ta...",You've been threatening to tell me the truth a...
2,"Maintenant, la seule chose qui compte est la m...","Right now, the only thing that matters Is the ..."
3,Ton mari... Trouver qui il est et pour qui il ...,Finding out who he is and who he works for.
4,Savez-vous où le prisonnier est emmené ?,Do you know where the prisoner was transported...
...,...,...
755691,Fils de Rufus B. et de son épouse Mary.,Son of Rufus B. And his wife Mary.
755692,"Si vous aviez vu Freddie, vous ne l'auriez pas...","""If you had seen Freddie, you would not."" ""Tru..."
755693,"- Fantastique. Ah, dommage que je l'ai pas vue...","""Oh, what a pity I did not see you then ..."""
755694,- J'aime regarder les jolies filles...,- I like to look pretty girls ...
755695,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [12]:
def shift_punctuation(text):
    # Fix "word .word" -> "word. word" and "word ,word" -> "word, word"
    text = re.sub(r'\s+([.,])', r'\1', text)      # Remove space before punctuation
    text = re.sub(r'([.,])(\w)', r'\1 \2', text)  # Ensure space after punctuation if followed by a word
    return text
df['english'] = df['english'].apply(shift_punctuation)
df['french'] = df['french'].apply(shift_punctuation)
df

,french,english
0,Je peux seulement te mener vers la vérité.,I can't make you believe it.
1,"Elizabeth Keen n'est pas ta femme, elle est ta...",You've been threatening to tell me the truth a...
2,"Maintenant, la seule chose qui compte est la m...","Right now, the only thing that matters Is the ..."
3,Ton mari... Trouver qui il est et pour qui il ...,Finding out who he is and who he works for.
4,Savez-vous où le prisonnier est emmené ?,Do you know where the prisoner was transported...
...,...,...
755691,Fils de Rufus B. et de son épouse Mary.,Son of Rufus B. And his wife Mary.
755692,"Si vous aviez vu Freddie, vous ne l'auriez pas...","""If you had seen Freddie, you would not."" ""Tru..."
755693,"- Fantastique. Ah, dommage que je l'ai pas vue...","""Oh, what a pity I did not see you then..."""
755694,- J'aime regarder les jolies filles...,- I like to look pretty girls...
755695,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [13]:
def capitalize_standalone_i(text):
    # Replace ' i ' with ' I '
    # Also handle ' i.' ' i,' ' i!' etc. at the end of a sentence
    return re.sub(r'(?<=\s)i(?=\s|[.,!?;:])', 'I', text)
df['english'] = df['english'].apply(capitalize_standalone_i)
df['french'] = df['french'].apply(capitalize_standalone_i)
df

,french,english
0,Je peux seulement te mener vers la vérité.,I can't make you believe it.
1,"Elizabeth Keen n'est pas ta femme, elle est ta...",You've been threatening to tell me the truth a...
2,"Maintenant, la seule chose qui compte est la m...","Right now, the only thing that matters Is the ..."
3,Ton mari... Trouver qui il est et pour qui il ...,Finding out who he is and who he works for.
4,Savez-vous où le prisonnier est emmené ?,Do you know where the prisoner was transported...
...,...,...
755691,Fils de Rufus B. et de son épouse Mary.,Son of Rufus B. And his wife Mary.
755692,"Si vous aviez vu Freddie, vous ne l'auriez pas...","""If you had seen Freddie, you would not."" ""Tru..."
755693,"- Fantastique. Ah, dommage que je l'ai pas vue...","""Oh, what a pity I did not see you then..."""
755694,- J'aime regarder les jolies filles...,- I like to look pretty girls...
755695,"Lâchez-moi, vous êtes un étranger !","- Release me, you're a stranger!"

In [15]:
# Print the sentence at row 20 (index 19)
print(df.iloc[11111]['english'])
print(df.iloc[11111]['french'])

This is the dirtiest job I've ever tackled.
C'est le plus sale boulot de ma vie.

In [14]:
len(df)

755696

In [16]:
df.to_csv(r"E:\nmt dataset\filtered_data that can be used\normalized_parallel\open_subtitle.csv", index=False, encoding="utf-8")